[airports]
khaf = 0
ksql = 1
knuq = 2
ksjc = 3
krhv = 4
ke16 = 5
kmce = 6
kmod = 7
ktcy = 8
klvk = 9
khwd = 10
ksfo = 11
koak = 12
kc83 = 13
ksck = 14
ko22 = 15
kcpu = 16
kccr = 17
kdvo = 18
ko69 = 19
ksts = 20
kapc = 21
ksuu = 22
kvcb = 23
kedu = 24
ksmf = 25
kmcc = 26
ksac = 27
kmhr = 28
ko61 = 29
kjaq = 30
kpvf = 31
kaun = 32
klhm = 33
kmyv = 34
kbab = 35
kgoo = 36
kblu = 37
kove = 38
kcic = 39
krbl = 40
k4b8 = 41

[settings]
lightning = True
papertrail = False
wind = True
brightness = 130
metar_refresh_rate = 300
sources = NOAA,Mesotech

[legend]
UNKNOWN = 29
